name: gnome-next-meeting-applet
buildsystem: simple
build-commands:
  - pip3 install --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} gnome_next_meeting_applet --no-build-isolation
  - cp -a images/  ${FLATPAK_DEST}/share/icons/gnome-next-meeting-applet
  - install -Dp -m644 desktop/icon.svg ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps/com.chmouel.gnomeNextMeetingApplet.svg
  - install -Dp -m644 desktop/com.chmouel.gnomeNextMeetingApplet.appdata.xml ${FLATPAK_DEST}/share/metainfo
  - install -Dp -m644 desktop/com.chmouel.gnomeNextMeetingApplet.desktop ${FLATPAK_DEST}/share/applications/
  - desktop-file-edit --set-key=Icon --set-value=com.chmouel.gnomeNextMeetingApplet ${FLATPAK_DEST}/share/applications/com.chmouel.gnomeNextMeetingApplet.desktop
sources:
  ## Dev
  - type: dir
    path: ../../dist

  ## Dev
  - type: dir
    path: ../../data
