name: Pylint Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install poetry pylint
      run: |
        python -m pip install --upgrade poetry
        poetry install -v
    - name: Test code
      run: |
        poetry run pytest
    - name: Lint code
      run: |
        poetry run pylint -r y gnma
